spring:
  application:
    name: minio
  servlet:
    multipart:
      max-file-size: 600GB
      max-request-size: 600GB
      enabled: true
      file-size-threshold: 600GB
minio:
  endpoint: http://localhost:9999
  accessKey: admin
  secretKey: 12345678
  bucketName: test-img